Implemented GUI, updated readme, updated region growing to accept multiple seeds
ZhiangChen/rock_detection_3d pull request #9
Opened 2024-07-23 16:53 UTC by deeprodge

2024-07-23 17:18 UTC, ZhiangChen requested changes
good job.

I had a minor comment.

also, please add the GUI workflow diagram

2024-07-23 17:18 UTC, ZhiangChen commented on unsupervised_rock_detection_3d/README.md
> +To enhance usability and enable interactive feedback, we have also developed a Graphical User Interface (GUI). The GUI allows geologists and students to run segmentation algorithms, visualize each st
feedback may cause some confusion, e.g., education feedback, feedback control, 

we can change it to "control"

2024-07-24 16:18 UTC, deeprodge commented on unsupervised_rock_detection_3d/README.md
> +To enhance usability and enable interactive feedback, we have also developed a Graphical User Interface (GUI). The GUI allows geologists and students to run segmentation algorithms, visualize each st
I've updated the readme. Please have a look and let me know.

2024-07-24 22:47 UTC, ZhiangChen approved these changes

2024-07-24 22:47 UTC, merged